services:
  documents.webapi:
    image: cr.yandex/crp27kpk2sn9vrc074jh/documents.webapi:latest
    container_name: "documents.webapi"
    ports:
      - 5052:8080
    build:
      context: .
      dockerfile: ./Documents.WebApi/Dockerfile
      args:
        - BUILD_CONFIGURATION=Debug #Debug, Release
        - ASPNETCORE_ENVIRONMENT=Development #Development, Staging, Production
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/KyrProjDB.db
    networks:
      - slavonic_recognition-documents
    volumes:
      - sqlite-data:/app/data
      - tune-data:/tmp/tune_model
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 3
    depends_on:
      documents.rabbitmq:
        condition: service_healthy

  documents.spa:
    image: cr.yandex/crp27kpk2sn9vrc074jh/documents.spa:latest
    container_name: "documents.spa"
    ports:
      - "5173:5173"
    build:
      context: ../DocumentRecognition_Spa_v2
      dockerfile: Dockerfile
    volumes:
      - ../DocumentRecognition_Spa_v2:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - slavonic_recognition-documents
    depends_on:
      - documents.webapi

  documents.recognition.ai:
    image: cr.yandex/crp27kpk2sn9vrc074jh/documents.recognition.ai:latest
    container_name: "documents.recognition.ai"
    build:
      context: ../DocumentRecognition.AI
      dockerfile: Dockerfile
    networks:
      - slavonic_recognition-documents
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M      
    volumes:
      - ../DocumentRecognition.AI:/app
      - sqlite-data:/app/data
      - tune-data:/tmp/tune_model
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=admin123
      - RABBITMQ_QUEUE_RECOGNITION_REQUEST=RecognitionRequest.Queue
      - RABBITMQ_QUEUE_RECOGNITION_RESULTS=RecognitionResults.Queue
      - RABBITMQ_QUEUE_TUNE_REQUEST=TuneRequest.Queue
      - DB_CONNECTION_STRING=/app/data/DocumentRecognitionAi.db
    depends_on:
      documents.rabbitmq:
        condition: service_healthy

  documents.rabbitmq:
    container_name: "documents.rabbitmq"
    image: rabbitmq:3.13-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - slavonic_recognition-documents
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  sqlite-data:
    driver: local
  tune-data:
    driver: local

networks:
  slavonic_recognition-documents:
    driver: bridge