services:
  documents.webapi:
    # image: ${DOCKER_REGISTRY-}documentswebapi
    ports:
        - 5052:5052
    build:
      context: .
      dockerfile: Documents.WebApi/Dockerfile
      args:
        - BUILD_CONFIGURATION=Debug #Debug, Release
        - ASPNETCORE_ENVIRONMENT=Development #Development, Staging, Production
        - ASPNETCORE_URLS=http://*:5052
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/KyrProjDB.db
    networks:
      - slavonic_recognition-documents
    volumes:
      - sqlite-data:/app/data

volumes:
  sqlite-data:
    driver: local

networks:
  slavonic_recognition-documents:
    driver: bridge