// <auto-generated />
using System;
using Documents.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Documents.Database.Migrations
{
    [DbContext(typeof(DocumentContext))]
    [Migration("20260608145108_TunedDocumentPrediction_Init")]
    partial class TunedDocumentPrediction_Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Documents.Database.Entity.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FileBlob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectedModelType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Documents.Database.Entity.DocumentPrediction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModelType")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Prob")
                        .HasColumnType("REAL");

                    b.Property<int>("RecognitionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DocumentPredictions");
                });

            modelBuilder.Entity("Documents.Database.Entity.TunedDocumentPrediction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DocumentPredictionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TunedDocumentPredictions");
                });
#pragma warning restore 612, 618
        }
    }
}
